test-real:
  stage: test
  image:
    name: dolfinx/dolfinx
    entrypoint: [""]
  before_script:
    - export PETSC_ARCH=linux-gnu-complex-32
    - git clone https://github.com/fenics/dolfinx.git
    - cd dolfinx
    - mkdir build
    - cd build
    - cmake -G Ninja ../cpp
    - ninja ${MAKEFLAGS} install
    - cd ../python
    - source /usr/local/share/dolfinx/dolfinx.conf
    - pip3 install .
    - cd ../../
    - mkdir -p build
    - cd build
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Developer ../cpp/
    - ninja -j3 install
    - cd ../python
    - pip3 install -e . --upgrade

  script:
    - flake8 .
    - cd tests
    - python3 -m pytest .
    - mpirun -n 2 python3 -m pytest .
    - mpirun -n 3 python3 -m pytest .
    - mpirun -n 4 python3 -m pytest .
    - cd ../demos
    - mkdir meshes
    - mkdir results
    - python3 demo_elasticity.py
    - mpirun -n 4 python3 demo_elasticity.py
    - python3 demo_periodic.py
    - mpirun -n 4 python3 demo_periodic.py
    - python3 demo_stokes.py
    - mpirun -n 4 python3 demo_stokes.py
    - python3 demo_periodic3d.py
    - mpirun -n 4 python3 demo_periodic3d.py
    - cd cubes
    - mkdir meshes
    - mkdir results
    - python3 rotated_cube.py
    - python3 rotated_cube3D.py
