fast-complex:
  stage: test
  tags:
    - docker
  except:
    - schedules
  image:
    name: dolfinx/dolfinx:v0.2.0a0
    entrypoint: [""]
  variables:
    PETSC_ARCH: "linux-gnu-complex-32"
    PYTHONPATH: "/usr/local/dolfinx-complex/lib/python3.8/dist-packages:/usr/local/lib"
    CC: mpicc
    HDF5_MPI: "ON"
    HDF5_DIR: "/usr/lib/x86_64-linux-gnu/hdf5/mpich/"
  before_script:
    - flake8 .
    - export PETSC_ARCH="linux-gnu-complex-32"
    - export LD_LIBRARY_PATH="/usr/local/petsc/linux-gnu-complex-32/lib/:/usr/local/dolfinx-complex/lib/:/usr/lib/x86_64-linux-gnu/hdf5/mpich/:$LD_LIBRARY_PATH"
    - export PATH="/usr/local/dolfinx-complex/bin:$PATH"
    - export PKG_CONFIG_PATH="/usr/local/dolfinx-complex/lib/pkgconfig:$PKG_CONFIG_PATH"
    - mkdir -p build
    - cd build
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Developer ../cpp/
    - ninja -j3 install
    - cd ../python
    - pip3 install -e . --upgrade
    - pip3 install --no-binary=h5py h5py

  script:
    - cd tests
    - python3 -m pytest .
    - mpirun -n 2 python3 -m pytest .
    - mpirun -n 3 python3 -m pytest .
    - mpirun -n 4 python3 -m pytest .
    - cd ../benchmarks
    - mkdir results
    - mkdir meshes
    - mpirun -n 4 python3 bench_periodic.py --nref=2 --tet --gamg --timings
    - mpirun -n 4 python3 bench_elasticity_edge.py --nref=2 --gamg --timings
    - mpirun -n 4 python3 bench_contact_3D.py
    - cd ../demos
    - mkdir meshes
    - mkdir results
    - python3 demo_elasticity.py
    - mpirun -n 4 python3 demo_elasticity.py
    - python3 demo_periodic_geometrical.py
    - mpirun -n 4 python3 demo_periodic_geometrical.py
    - python3 demo_stokes.py
    - mpirun -n 4 python3 demo_stokes.py
    - python3 demo_periodic3d_topological.py
    - mpirun -n 4 python3 demo_periodic3d_topological.py
    - python3 demo_elasticity_disconnect_2D.py
    - mpirun -n 4 python3 demo_elasticity_disconnect_2D.py
    - python3 demo_elasticity_disconnect.py
    - mpirun -n 4 python3 demo_elasticity_disconnect.py
    - make contact2D-serial
    - make contact2D-parallel
    - make contact3D-serial
    - make contact3D-parallel

fast-real:
  stage: test
  tags:
    - docker
  except:
    - schedules
  image:
    name: dolfinx/dolfinx:v0.2.0a0
    entrypoint: [""]
  variables:
    PETSC_ARCH: "linux-gnu-real-32"
    PYTHONPATH: "/usr/local/dolfinx-real/lib/python3.8/dist-packages:/usr/local/lib"
    CC: mpicc
    HDF5_MPI: "ON"
    HDF5_DIR: "/usr/lib/x86_64-linux-gnu/hdf5/mpich/"
  before_script:
    - flake8 .
    - export LD_LIBRARY_PATH="/usr/local/petsc/linux-gnu-real-32/lib/:/usr/local/dolfinx-real/lib/:/usr/lib/x86_64-linux-gnu/hdf5/mpich/:$LD_LIBRARY_PATH"
    - export PATH="/usr/local/dolfinx-real/bin:$PATH"
    - export PKG_CONFIG_PATH="/usr/local/dolfinx-real/lib/pkgconfig:$PKG_CONFIG_PATH"
    - mkdir -p build
    - cd build
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Developer ../cpp/
    - ninja -j3 install
    - cd ../python
    - pip3 install -e . --upgrade
    - pip3 install --no-binary=h5py h5py


  script:
    - cd tests
    - python3 -m pytest .
    - mpirun -n 2 python3 -m pytest .
    - mpirun -n 3 python3 -m pytest .
    - mpirun -n 4 python3 -m pytest .
    - cd ../benchmarks
    - mkdir results
    - mkdir meshes
    - mpirun -n 4 python3 bench_periodic.py --nref=2 --tet --gamg --timings
    - mpirun -n 4 python3 bench_elasticity_edge.py --nref=2 --gamg --timings
    - mpirun -n 4 python3 bench_contact_3D.py
    - cd ../demos
    - mkdir meshes
    - mkdir results
    - python3 demo_elasticity.py
    - mpirun -n 4 python3 demo_elasticity.py
    - python3 demo_periodic_geometrical.py
    - mpirun -n 4 python3 demo_periodic_geometrical.py
    - python3 demo_stokes.py
    - mpirun -n 4 python3 demo_stokes.py
    - python3 demo_periodic3d_topological.py
    - mpirun -n 4 python3 demo_periodic3d_topological.py
    - python3 demo_elasticity_disconnect_2D.py
    - mpirun -n 4 python3 demo_elasticity_disconnect_2D.py
    - python3 demo_elasticity_disconnect.py
    - mpirun -n 4 python3 demo_elasticity_disconnect.py
    - make contact2D-serial
    - make contact2D-parallel
    - make contact3D-serial
    - make contact3D-parallel
