name: Test Python assemblers

on:
  # Trigger tests on push
  push:
    branches:
      - "**"
  schedule:
    # '*' is a special character in YAML, so string must be quoted
    - cron: "0 1 * * *"
jobs:
  build:
    if: "!(contains(github.event.head_commit.message, '[ci skip]') || contains(github.event.head_commit.message, '[skip ci]'))"
    runs-on: ubuntu-20.04
    container: dolfinx/dolfinx:v0.2.0a0
    env:
      CC: mpicc
      PETSC_ARCH: linux-gnu-real-32
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      OMPI_MCA_rmaps_base_oversubscribe: 1
      OMPI_MCA_plm: isolated
      OMPI_MCA_btl_vader_single_copy_mechanism: none
      OMPI_MCA_mpi_yield_when_idle: 1
      OMPI_MCA_hwloc_base_binding_policy: none
      HDF5_MPI: "ON"
      HDF5_DIR: "/usr/lib/x86_64-linux-gnu/hdf5/mpich/"
    steps:
      - uses: actions/checkout@v2

      - name: Install benchmark dependencies
        run: | 
          pip3 install --no-binary=h5py h5py

      - name: Install dolfinx_mpc (C++)
        run: |
          cmake -G Ninja -B build-dir -DCMAKE_BUILD_TYPE=Developer cpp/
          ninja -C build-dir install
      - name: Install dolfinx_mpc (Python)
        run: python3 -m pip -v install python/

      - name: Flake8 code
        run: flake8 python/

      - name: Run tests and demos
        run: |
          cd python/tests
          python3 -m pytest . -vs
          mpirun -n 2 python3 -m pytest .
          mpirun -n 3 python3 -m pytest .
          mpirun -n 4 python3 -m pytest .
          cd ../benchmarks
          mkdir results
          mkdir meshes
          mpirun -n 4 python3 bench_periodic.py --nref=2 --tet --gamg --timings
          mpirun -n 4 python3 bench_elasticity_edge.py --nref=2 --gamg --timings
          mpirun -n 4 python3 bench_contact_3D.py
          cd ../demos
          mkdir meshes
          mkdir results
          python3 demo_elasticity.py
          mpirun -n 4 python3 demo_elasticity.py
          python3 demo_periodic_geometrical.py
          mpirun -n 4 python3 demo_periodic_geometrical.py
          python3 demo_stokes.py
          mpirun -n 4 python3 demo_stokes.py
          python3 demo_periodic3d_topological.py
          mpirun -n 4 python3 demo_periodic3d_topological.py
          python3 demo_elasticity_disconnect_2D.py
          mpirun -n 4 python3 demo_elasticity_disconnect_2D.py
          python3 demo_elasticity_disconnect.py
          mpirun -n 4 python3 demo_elasticity_disconnect.py
          make contact2D-serial
          make contact2D-parallel
          make contact3D-serial
          make contact3D-parallel
